import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/common/layout/Navbar";
import { Footer } from "@/common/layout/Footer";
import { TranslationProvider } from "@/common/context/translation-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TranslationProvider>
          <Navbar />
          {children}
          <Footer />
        </TranslationProvider>
      </body>
    </html>
  );
}
